### ISSUE TITLE
Add `profile_ranking_avg` and `reduction_targets_avg` columns at company level in emission and sector profile indictors repectively

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicatorAfter#161]
Relates to [comment](https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/152#discussion_r1486251040)

**Comment by maurolepore** [comment]
> didn't see an approach that could have just work just fine (rather I only saw a complex solution)

Yeah, I hear you. I see this in a separate PR where adding a jittered co2-range was pretty difficult. To me that signals we need to refactor the code so that that, this, and future changes are easier to implement. Right now we seems to not have much time for a deep refactoring but I make a mental note to do it as soon as we can.
